### ISSUE TITLE
You can't create a function without arguments

### ISSUE THREAD

**Issue by mangodev01** [sebbekarlsson/hello#6]
when you try to create a function without arguments (eg.
```
function printHello() {
    print("Hello!");
}
```
) it says "Unexpected token `)`, with type 5", so the examples/functions.hello example wouldn't work.

**Comment by YxnnXriel** [comment]
yes yes you're right, I don't know if it will continue the series but you can FORK the project and in the **parser.c** file in the **parser_parse_function_definition** function add after the `parser_eat(parser, TOKEN_LPAREN);` `if (parser->current_token->type ! = TOKEN_RPAREN)` , you'll move all subsequent code in the condition we've just created to this: `parser_eat(parser, TOKEN_RPAREN);` . After that, it should pass.

**Comment by mangodev01** [comment]
> yes yes you're right, I don't know if it will continue the series but you can FORK the project and in the **parser.c** file in the **parser_parse_function_definition** function add after the `parser_eat(parser, TOKEN_LPAREN);` `if (parser->current_token->type ! = TOKEN_RPAREN)` , you'll move all subsequent code in the condition we've just created to this: `parser_eat(parser, TOKEN_RPAREN);` . After that, it should pass.

thanks.
